// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Taxi24.Servicios.Facturas.Data;

namespace Taxi24.Servicios.Facturas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210506213625_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Taxi24.Servicios.Facturas.Entities.Factura", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("ConductorID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Monto")
                        .HasColumnType("double precision");

                    b.Property<long>("ViajeID")
                        .HasColumnType("bigint");

                    b.Property<long>("ViajeroID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
