--
-- PostgreSQL database dump
--

-- Dumped from database version 12.4 (Debian 12.4-1.pgdg100+1)
-- Dumped by pg_dump version 13.2

-- Started on 2021-05-07 01:08:49 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 204 (class 1259 OID 16410)
-- Name: Facturas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Facturas" (
    "ID" bigint NOT NULL,
    "Fecha" timestamp without time zone NOT NULL,
    "ViajeID" bigint NOT NULL,
    "ConductorID" bigint NOT NULL,
    "ViajeroID" bigint NOT NULL,
    "Monto" double precision NOT NULL,
    "EmpresaID" bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public."Facturas" OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 16408)
-- Name: Facturas_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Facturas" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Facturas_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 16403)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 2914 (class 0 OID 16410)
-- Dependencies: 204
-- Data for Name: Facturas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Facturas" ("ID", "Fecha", "ViajeID", "ConductorID", "ViajeroID", "Monto", "EmpresaID") FROM stdin;
1	2021-05-07 00:59:39.416507	1	4	1	234.083324	1
2	2021-05-07 01:00:41.201587	34	4	1	53.3811021	1
\.


--
-- TOC entry 2912 (class 0 OID 16403)
-- Dependencies: 202
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20210506213625_init	5.0.5
20210506214539_add-field	5.0.5
\.


--
-- TOC entry 2920 (class 0 OID 0)
-- Dependencies: 203
-- Name: Facturas_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Facturas_ID_seq"', 2, true);


--
-- TOC entry 2785 (class 2606 OID 16414)
-- Name: Facturas PK_Facturas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Facturas"
    ADD CONSTRAINT "PK_Facturas" PRIMARY KEY ("ID");


--
-- TOC entry 2783 (class 2606 OID 16407)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2021-05-07 01:08:49 UTC

--
-- PostgreSQL database dump complete
--

