--
-- PostgreSQL database dump
--

-- Dumped from database version 12.4 (Debian 12.4-1.pgdg100+1)
-- Dumped by pg_dump version 13.2

-- Started on 2021-05-11 00:40:00 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 204 (class 1259 OID 16438)
-- Name: Viajes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Viajes" (
    "ID" bigint NOT NULL,
    "EmpresaID" bigint NOT NULL,
    "PilotoID" bigint NOT NULL,
    "PasajeroID" bigint NOT NULL,
    "Inicio" timestamp without time zone,
    "Final" timestamp without time zone
);


ALTER TABLE public."Viajes" OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 16436)
-- Name: Viaje_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Viajes" ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Viaje_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 16431)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 2913 (class 0 OID 16438)
-- Dependencies: 204
-- Data for Name: Viajes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Viajes" ("ID", "EmpresaID", "PilotoID", "PasajeroID", "Inicio", "Final") VALUES (1, 1, 4, 1, '2021-05-07 00:55:44.876639', '2021-05-07 00:59:38.959963');
INSERT INTO public."Viajes" ("ID", "EmpresaID", "PilotoID", "PasajeroID", "Inicio", "Final") VALUES (34, 1, 4, 1, '2021-05-07 00:59:47.729495', '2021-05-07 01:00:41.110597');


--
-- TOC entry 2911 (class 0 OID 16431)
-- Dependencies: 202
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20210506155247_init', '5.0.5');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20210506193959_rename', '5.0.5');


--
-- TOC entry 2919 (class 0 OID 0)
-- Dependencies: 203
-- Name: Viaje_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Viaje_ID_seq"', 34, true);


--
-- TOC entry 2784 (class 2606 OID 16444)
-- Name: Viajes PK_Viajes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Viajes"
    ADD CONSTRAINT "PK_Viajes" PRIMARY KEY ("ID");


--
-- TOC entry 2782 (class 2606 OID 16435)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2021-05-11 00:40:00 UTC

--
-- PostgreSQL database dump complete
--

